# We need a Docker image to be built and stored in order to run e2e tests
name: Docker Build

on:
    push:
        branches:
            - "**"

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Get branch name
              id: branch-name
              uses: tj-actions/branch-names@v5.1
            - name: Make branch name compatible
              id: clean-branch
              run: |
                  BRANCH=${{ steps.branch-name.outputs.current_branch }}
                  BRANCH_CLEAN="${BRANCH//\//-}"
                  echo "clean_branch=${BRANCH_CLEAN}" >> $GITHUB_ENV
                  echp "Cleaned branch name from $BRANCH to $BRANCH_CLEAN"
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: 0xjem/olympus-contracts:${{ env.clean_branch }}
